apiVersion: v1
kind: Service
metadata:
  name: otus-crud-server-service
spec:
  type: NodePort
  selector:
    app: otus-crud-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000